---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-ui-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy-ui-simple
  template:
    metadata:
      labels:
        app: canopy-ui-simple
    spec:
      containers:
        - name: canopy-ui-simple
          image: {{ .Values.image }}
          ports:
            - containerPort: 8501
          env:
            - name: LLM_ENDPOINT
              value: "{{ .Values.LLM_ENDPOINT }}"
            - name: SYSTEM_PROMPT
              value: "{{ .Values.SYSTEM_PROMPT}}"
            - name: MODEL_NAME
              value: "{{ .Values.MODEL_NAME }}"
