---
apiVersion: v1
kind: Service
metadata:
  name: canopy-ui-simple
  labels:
    app: canopy-ui-simple
spec:
  selector:
    app: canopy-ui-simple
  ports:
    - name: http
      port: 80
      targetPort: 8501
  type: ClusterIP
